// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdaQs9GsNMy9fln5AQXNg4yAJQJfNfZDg',
    appId: '1:760693782485:web:0eb3d7910b8dc0a3306f5c',
    messagingSenderId: '760693782485',
    projectId: 'cnumontifier',
    authDomain: 'cnumontifier.firebaseapp.com',
    storageBucket: 'cnumontifier.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZosLu-U9SELC4UaoluZb7mQU7mmHLhk4',
    appId: '1:760693782485:android:c7f4943ab2bb24bd306f5c',
    messagingSenderId: '760693782485',
    projectId: 'cnumontifier',
    storageBucket: 'cnumontifier.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL-T7DbUel8Y5j3ytSw2HxgOnBkwT86ow',
    appId: '1:760693782485:ios:788a83dbee1cc808306f5c',
    messagingSenderId: '760693782485',
    projectId: 'cnumontifier',
    storageBucket: 'cnumontifier.appspot.com',
    androidClientId: '760693782485-th3gnrdqcouas7s7litla6ji4q9e3nbl.apps.googleusercontent.com',
    iosClientId: '760693782485-g9k9m4sf22m8kvsqmll0rjqcuk4j3j6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.cnumontifier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL-T7DbUel8Y5j3ytSw2HxgOnBkwT86ow',
    appId: '1:760693782485:ios:95ee4702b4a64d35306f5c',
    messagingSenderId: '760693782485',
    projectId: 'cnumontifier',
    storageBucket: 'cnumontifier.appspot.com',
    androidClientId: '760693782485-th3gnrdqcouas7s7litla6ji4q9e3nbl.apps.googleusercontent.com',
    iosClientId: '760693782485-3qgrm7u3bof71g4sqk1jqa8kbhoek16t.apps.googleusercontent.com',
    iosBundleId: 'com.example.cnumontifier.RunnerTests',
  );
}
